#pragma once
#include <Arduino.h>

// Score 1 = safe / read-only, 5 = destructive / irreversible.
// Multi-token entries (e.g. "rm -rf") are matched as a whole phrase with
// word boundaries on both ends, so "rm -rf" matches "sudo rm -rf /" but
// keyword "rm" does NOT match "lrm" or "warm".
struct CommandEntry {
  const char *keyword;
  uint8_t score;
};

static const CommandEntry kCommandTable[] = {
  // 5 — destructive / irreversible
  {"rm -rf",            5},
  {"rm -fr",            5},
  {"rm -r",             5},
  {"rm",                5},
  {"shred",             5},
  {"mkfs",              5},
  {"dd",                5},
  {"wipefs",            5},
  {"mkswap",            5},
  {"fdisk",             5},
  {"parted",            5},
  {"gdisk",             5},
  {"sgdisk",            5},
  {"cryptsetup",        5},
  {"shutdown",          5},
  {"reboot",            5},
  {"halt",              5},
  {"poweroff",          5},
  {"init 0",            5},
  {"init 6",            5},
  {"userdel",           5},
  {"crontab -r",        5},
  {":(){",              5}, // fork bomb hint
  // git — history / ref rewriting, irrecoverable refs
  {"git push --force",  5},
  {"git push -f",       5},
  {"git push --force-with-lease", 5},
  {"git push --delete", 5},
  {"git push --mirror", 5},
  {"git reset --hard",  5},
  {"git clean -fd",     5},
  {"git clean -f",      5},
  {"git branch -D",     5},
  {"git filter-branch", 5},
  {"git filter-repo",   5},
  {"git reflog expire", 5},
  {"git gc --prune=now",5},
  {"git update-ref -d", 5},
  {"git worktree remove --force", 5},
  // database
  {"drop table",        5},
  {"drop database",     5},
  {"truncate",          5},
  {"delete from",       5},
  {"flushall",          5},
  {"flushdb",           5},
  // IaC / orchestration
  {"terraform destroy", 5},
  {"pulumi destroy",    5},
  {"kubectl delete",    5},
  {"helm uninstall",    5},
  {"helm delete",       5},
  // AWS — S3 / IAM
  {"aws s3 rm",         5},
  {"aws s3 rb",         5},
  {"aws s3api delete-bucket",  5},
  {"aws s3api delete-objects", 5},
  {"aws iam delete",    5},
  // AWS — RDS / DocumentDB (delete-* covered by `aws rds delete`)
  {"aws rds delete",    5},
  {"aws rds stop-db",   5}, // stop-db-instance, stop-db-cluster
  {"aws rds reboot-db", 5}, // reboot-db-instance, reboot-db-cluster
  {"aws rds failover-db-cluster", 5},
  {"aws rds promote-read-replica", 5},
  {"aws rds restore-db", 5}, // overwrites existing identifier paths
  {"aws docdb delete",  5},
  {"aws docdb stop-db", 5},
  {"aws neptune delete",5},
  // AWS — DynamoDB (delete-table / delete-item / delete-backup all caught)
  {"aws dynamodb delete",            5},
  {"aws dynamodb update-time-to-live", 5}, // enabling TTL silently mass-deletes
  {"aws dynamodb restore-table",     5},
  // AWS — EC2 / VPC
  {"aws ec2 terminate", 5},
  {"aws ec2 delete-volume",   5},
  {"aws ec2 delete-snapshot", 5},
  {"aws ec2 delete-vpc",      5},
  {"aws ec2 delete-subnet",   5},
  {"aws ec2 delete-network-interface", 5},
  // AWS — other services
  {"aws lambda delete",       5},
  {"aws cloudformation delete-stack", 5},
  {"aws cdk destroy",         5},
  {"aws kms schedule-key-deletion",   5},
  {"aws ecr delete",          5},
  {"aws ecr batch-delete-image", 5},
  {"aws ecs delete",          5},
  {"aws eks delete",          5},
  {"aws elasticache delete",  5},
  {"aws redshift delete",     5},
  {"aws secretsmanager delete-secret", 5},
  {"aws ssm delete-parameter",5},
  {"aws route53 delete-hosted-zone",  5},
  {"aws backup delete",       5},
  {"aws glue delete",         5},
  {"aws emr terminate-clusters", 5},
  // containers
  {"docker system prune", 5},
  {"docker volume rm",  5},
  {"docker volume prune", 5},
  {"docker compose down -v", 5},
  // publishing — irreversible to a public namespace
  {"npm publish",       5},
  {"cargo publish",     5},
  {"twine upload",      5},
  // PowerShell / Windows
  {"remove-item -recurse -force", 5},
  {"remove-item -force -recurse", 5},
  {"format-volume",     5},
  {"clear-disk",        5},
  {"diskpart",          5},
  {"stop-computer",     5},
  {"restart-computer",  5},
  {"reg delete",        5},
  {"cipher /w",         5},
  {"sdelete",           5},

  // macOS / Darwin
  {"diskutil eraseDisk",      5},
  {"diskutil eraseVolume",    5},
  {"diskutil secureErase",    5},
  {"diskutil partitionDisk",  5},
  {"diskutil apfs delete",    5}, // deleteContainer / deleteVolume
  {"diskutil unmountDisk force", 5},
  {"tmutil delete",           5},
  {"tmutil disable",          5},
  {"csrutil disable",         5}, // disables System Integrity Protection
  {"csrutil clear",           5},
  {"spctl --master-disable",  5}, // disables Gatekeeper
  {"nvram -c",                5},
  {"bless --device",          5},
  {"srm",                     5}, // secure remove (BSD)

  // Cloudflare — wrangler / cloudflared / flarectl
  {"wrangler delete",                  5},
  {"wrangler kv:namespace delete",     5},
  {"wrangler kv namespace delete",     5}, // v3 space syntax
  {"wrangler r2 bucket delete",        5},
  {"wrangler d1 delete",               5},
  {"wrangler queues delete",           5},
  {"wrangler vectorize delete",        5},
  {"wrangler hyperdrive delete",       5},
  {"wrangler pages project delete",    5},
  {"wrangler workflows delete",        5},
  {"cloudflared tunnel delete",        5},
  {"flarectl zone delete",             5}, // nukes an entire CF zone

  // git — more destructive
  {"git rm -rf",                  5},
  {"git rm -fr",                  5},
  {"git submodule deinit --force",5},
  {"git submodule deinit -f",     5},

  // GitHub CLI (gh) — destructive
  {"gh repo delete",   5},
  {"gh repo transfer", 5}, // changes ownership, can't easily undo
  {"gh release delete",5},
  {"gh issue delete",  5},

  // SSH / sync — destructive transport-side
  {"rsync --delete",          5}, // syncs deletions from src to dst
  {"rsync --delete-after",    5},
  {"rsync --delete-before",   5},
  {"rsync --delete-during",   5},
  {"rsync --delete-excluded", 5},
  {"rsync --remove-source-files", 5},
  // GPG / keystore — destructive
  {"gpg --delete-keys",        5},
  {"gpg --delete-secret-keys", 5},
  {"keytool -delete",          5},
  // boot
  {"efibootmgr -B",   5}, // deletes a UEFI boot entry
  {"bcdedit /delete", 5}, // Windows boot store
  {"grub-install",    5},
  // LVM / ZFS / btrfs / RAID — irreversible storage ops
  {"lvremove",        5},
  {"vgremove",        5},
  {"pvremove",        5},
  {"zfs destroy",     5},
  {"zpool destroy",   5},
  {"btrfs subvolume delete", 5},
  {"mdadm --zero-superblock", 5},
  {"mdadm --remove",  5},
  // filesystem mutations
  {"tar --remove-files", 5},
  // HTTP destructive
  {"curl -X DELETE",  5},
  {"http delete",     5}, // httpie
  // container escape risk
  {"docker run --privileged", 5},

  // ORM / migration destructive
  {"prisma migrate reset", 5},
  {"rails db:drop",        5},
  {"rails db:reset",        5},
  {"supabase db reset",     5},
  {"alembic downgrade base",5},
  {"sequelize db:drop",     5},

  // Kubernetes — node-level destructive
  {"kubectl drain",  5},

  // GCP
  {"gcloud projects delete",          5},
  {"gcloud compute instances delete", 5},
  {"gcloud sql instances delete",     5},
  {"gcloud sql databases delete",     5},
  {"gcloud container clusters delete",5},
  {"gcloud functions delete",         5},
  {"gcloud run services delete",      5},
  {"gcloud storage rm",               5},
  {"gsutil rm",                       5},
  {"gcloud iam service-accounts delete", 5},
  {"gcloud secrets delete",           5},
  {"gcloud pubsub topics delete",     5},
  // Azure
  {"az group delete",          5}, // deletes resource group + everything in it
  {"az vm delete",             5},
  {"az storage account delete",5},
  {"az sql server delete",     5},
  {"az sql db delete",         5},
  {"az cosmosdb delete",       5},
  {"az aks delete",            5},
  {"az functionapp delete",    5},
  {"az webapp delete",         5},
  {"az keyvault delete",       5},
  // DigitalOcean
  {"doctl droplet delete",            5},
  {"doctl databases delete",          5},
  {"doctl kubernetes cluster delete", 5},
  {"doctl apps delete",               5},
  // Fly.io
  {"fly apps destroy",     5},
  {"flyctl apps destroy",  5},
  {"fly volumes destroy",  5},
  {"fly machines destroy", 5},
  // Heroku
  {"heroku apps:destroy",    5},
  {"heroku pg:reset",        5},
  {"heroku addons:destroy",  5},
  // Vercel / Netlify / Firebase / Supabase
  {"vercel rm",                  5},
  {"vercel remove",              5},
  {"netlify sites:delete",       5},
  {"firebase functions:delete",  5},
  {"firebase projects:delete",   5},
  {"firebase firestore:delete",  5},
  {"firebase database:remove",   5},
  // SCM beyond git
  {"jj abandon",  5},

  // bazel / monorepo destructive
  {"bazel clean --expunge", 5},

  // 4 — mutates system / remote state
  {"sudo",              4},
  {"chmod",             4},
  {"chown",             4},
  {"kill",              4},
  {"killall",           4},
  {"pkill",             4},
  {"systemctl",         4},
  {"service",           4},
  {"apt",               4},
  {"apt-get",           4},
  {"yum",               4},
  {"dnf",               4},
  {"pacman",            4},
  {"npm uninstall",     4},
  {"pip uninstall",     4},
  {"mv",                4},
  {"passwd",            4},
  {"crontab -e",        4},
  {"-delete",           4}, // catches `find . -delete`, `--delete-branch`, etc.
  {"iptables -F",       4},
  {"nft flush",         4},
  {"ufw reset",         4},
  // git
  {"git push",          4},
  {"git reset",         4},
  {"git rebase",        4},
  {"git checkout .",    4},
  {"git restore .",     4},
  {"git stash drop",    4},
  {"git stash clear",   4},
  {"git tag -d",        4},
  // IaC / orchestration mutate
  {"terraform apply",   4},
  {"pulumi up",         4},
  {"kubectl apply",     4},
  {"kubectl scale",     4},
  {"kubectl rollout",   4},
  {"kubectl exec",      4},
  {"helm install",      4},
  {"helm upgrade",      4},
  // containers mutate
  {"docker rm -f",      4},
  {"docker rmi -f",     4},
  {"docker kill",       4},
  // PowerShell mutate
  {"stop-process",      4},
  {"stop-service",      4},
  {"invoke-expression", 4},
  // AWS — risky mutations / downtime (reversible but service-affecting)
  {"aws rds modify-db", 4},
  {"aws rds reset-db-parameter-group", 4},
  {"aws dynamodb update-table",     4},
  {"aws dynamodb batch-write-item", 4}, // can mass-delete via DeleteRequest
  {"aws ec2 stop-instances",        4},
  {"aws ec2 reboot-instances",      4},
  {"aws ec2 detach-volume",         4},
  {"aws ec2 revoke-security-group-ingress", 4},
  {"aws ec2 revoke-security-group-egress",  4},
  {"aws kms disable-key",           4},
  {"aws iam detach",                4}, // detach-role-policy, detach-user-policy, ...
  {"aws iam remove",                4},
  {"aws sns delete-topic",          4},
  {"aws sqs delete-queue",          4},
  {"aws sqs purge-queue",           4},
  {"aws cloudfront create-invalidation", 4}, // bills + can wipe caches
  {"aws route53 change-resource-record-sets", 4},
  {"aws cloudformation update-stack", 4}, // can replace/destroy resources
  {"aws ecs update-service",        4},
  // macOS — mutates system state
  {"defaults write",     4},
  {"defaults delete",    4},
  {"launchctl unload",   4},
  {"launchctl bootout",  4},
  {"launchctl disable",  4},
  {"dscl . -delete",     4}, // delete user / group via Directory Service
  {"sysadminctl -deleteUser", 4},
  {"dseditgroup -o delete",   4},
  {"tccutil reset",      4}, // resets per-app privacy permissions
  {"networksetup",       4},
  {"scutil --set",       4},
  {"pmset",              4},
  {"kextunload",         4},
  {"kextload",           4},
  {"mdutil -d",          4}, // disables Spotlight indexing
  // Cloudflare — mutates remote state
  {"wrangler secret delete",          4},
  {"wrangler kv:key delete",          4},
  {"wrangler kv key delete",          4},
  {"wrangler r2 object delete",       4},
  {"wrangler pages deployment delete",4},
  {"wrangler d1 execute",             4}, // can run destructive SQL
  {"flarectl dns delete",             4},
  {"cloudflared service uninstall",   4},

  // git — more mutating
  {"git rm",                      4},
  {"git submodule deinit",        4},
  {"git switch --discard-changes",4},
  {"git push --tags",             4},
  {"git remote remove",           4},
  {"git remote rm",               4},
  {"git remote prune",            4},
  {"git config --unset",          4},
  {"git config --system",         4},

  // GitHub CLI (gh) — mutates remote state
  {"gh pr merge",         4},
  {"gh pr close",         4},
  {"gh issue close",      4},
  {"gh secret set",       4}, // overwrites silently
  {"gh secret remove",    4},
  {"gh secret delete",    4},
  {"gh variable set",     4},
  {"gh variable remove",  4},
  {"gh repo edit",        4},
  {"gh repo archive",     4},
  {"gh repo rename",      4},
  {"gh release upload",   4},
  {"gh release edit",     4},
  {"gh run cancel",       4},
  {"gh workflow disable", 4},
  {"gh ssh-key delete",   4},
  {"gh gpg-key delete",   4},
  {"gh codespace delete", 4},

  // SSH agent / keys
  {"ssh-add -D",      4}, // wipes all identities from the agent
  {"ssh-add -d",      4},
  // privilege escalation
  {"su -",            4},
  {"sudo -i",         4},
  {"sudo -s",         4},
  // filesystem / boot
  {"mount",           4},
  {"umount",          4},
  {"fsck",            4},
  {"e2fsck",          4},
  {"tune2fs",         4},
  {"update-grub",     4},
  {"update-initramfs",4},
  {"mkinitcpio",      4},
  // Kubernetes — node / workload mutations
  {"kubectl edit",    4},
  {"kubectl cordon",  4},
  {"kubectl taint",   4},
  {"kubectl patch",   4},
  // container — registry push / kill / restart
  {"docker push",     4},
  {"docker restart",  4},
  // package manager risky updates
  {"npm audit fix --force",  4},
  {"bundle update",          4},
  {"cargo update",           4},
  {"poetry install --sync",  4}, // removes packages not in lockfile
  {"poetry remove",          4},
  {"go get -u",              4},
  // ORM / migration
  {"flyway migrate",     4},
  {"alembic upgrade",    4},
  {"alembic downgrade",  4},
  {"rails db:migrate",   4},
  {"rails db:rollback",  4},
  {"prisma db push",     4}, // --force-reset is destructive, but base form is risky
  // scheduling / shell
  {"at now",       4},
  {"systemd-run",  4},
  // tmux / screen — session destruction
  {"tmux kill-server",  4},
  {"tmux kill-session", 4},

  // 3 — writes locally, contained
  {"cp",                3},
  {"ln",                3},
  {"curl",              3},
  {"wget",              3},
  {"rsync",             3},
  {"scp",               3},
  {"git commit",        3},
  {"git checkout",      3},
  {"git restore",       3},
  {"git tag",           3},
  {"git revert",        3},
  {"git merge",         3},
  {"git pull",          3},
  {"git stash",         3},
  {"npm install",       3},
  {"pip install",       3},
  {"yarn",              3},
  {"pnpm",              3},
  {"brew",              3},
  {"composer",          3},
  {"bundle",            3},
  {"terraform init",    3},
  {"docker",            3},
  {"set-content",       3},
  {"out-file",          3},
  {"new-item",          3},
  {"invoke-webrequest", 3},
  // macOS
  {"osascript",         3},
  {"mas install",       3},
  {"port install",      3},
  {"pod install",       3},
  {"xcodebuild",        3},
  {"fastlane",          3},
  // Cloudflare
  {"wrangler deploy",      3},
  {"wrangler publish",     3},
  {"wrangler pages deploy",3},
  {"wrangler secret put",  3},
  {"wrangler kv:key put",  3},
  {"wrangler kv key put",  3},
  // git — more local writes
  {"git init",         3},
  {"git clone",        3},
  {"git switch",       3},
  {"git stash pop",    3},
  {"git stash apply",  3},
  {"git stash push",   3},
  {"git cherry-pick",  3},
  {"git apply",        3},
  {"git am",           3},
  {"git bisect",       3},
  // GitHub CLI (gh) — opens / edits / creates remote artifacts
  {"gh pr create",     3},
  {"gh pr edit",       3},
  {"gh pr review",     3},
  {"gh pr comment",    3},
  {"gh pr checkout",   3},
  {"gh pr ready",      3},
  {"gh issue create",  3},
  {"gh issue comment", 3},
  {"gh issue edit",    3},
  {"gh repo create",   3},
  {"gh repo fork",     3},
  {"gh repo clone",    3},
  {"gh release create",3},
  {"gh workflow run",  3},
  {"gh run rerun",     3},
  {"gh auth login",    3},
  {"gh extension install", 3},
  {"gh gist create",   3},
  {"gh codespace create",  3},

  // SSH — key / host management
  {"ssh-keygen",      3},
  {"ssh-keygen -R",   3},
  {"ssh-copy-id",     3},
  {"sftp",            3},
  // database CLIs (interactive — DROP/DELETE inside still scored 5 by SQL keywords)
  {"psql",            3},
  {"mysql",           3},
  {"mongosh",         3},
  {"mongo",           3},
  {"redis-cli",       3},
  {"sqlite3",         3},
  // package install / exec
  {"npm ci",          3},
  {"npx",             3},
  {"pnpm dlx",        3},
  // build tools
  {"mvn",             3},
  {"gradle",          3},
  {"bazel",           3},
  {"cmake",           3},
  {"ninja",           3},
  {"meson",           3},
  // bundlers / transpilers
  {"tsc",             3},
  {"vite",            3},
  {"webpack",         3},
  {"esbuild",         3},
  {"rollup",          3},
  {"parcel",          3},
  {"next",            3},
  // runtime version managers
  {"nvm install",     3},
  {"pyenv install",   3},
  {"rustup",          3},
  {"asdf install",    3},
  {"mise install",    3},
  // GPG
  {"gpg --import",    3},
  {"gpg --gen-key",   3},
  // archive
  {"tar -xf",         3},
  {"unzip -o",        3},
  {"gzip -f",         3},
  // misc
  {"prisma generate", 3},
  {"prisma db pull",  3},
  {"tee",             3},
  {"docker pull",     3},
  {"docker login",    3},
  {"docker tag",      3},
  // HTTP write methods
  {"curl -X POST",    3},
  {"curl -X PUT",     3},
  {"curl -X PATCH",   3},
  // in-place text editing — overrides `sed` (1) / `awk` (1)
  {"sed -i",          3},
  {"awk -i inplace",  3},
  // decompress in place (mutates source file)
  {"gunzip",          3},
  {"bunzip2",         3},
  {"unxz",            3},

  // 2 — runs code locally
  {"python",            2},
  {"python3",           2},
  {"node",              2},
  {"deno",              2},
  {"bash",              2},
  {"sh",                2},
  {"pwsh",              2},
  {"powershell",        2},
  {"ruby",              2},
  {"go run",            2},
  {"cargo run",         2},
  {"make",              2},
  {"mkdir",             2},
  {"touch",             2},
  // macOS dev runtime
  {"swift",             2},
  {"xcrun",             2},
  // test runners
  {"pytest",            2},
  {"jest",              2},
  {"vitest",            2},
  {"mocha",             2},
  {"rspec",             2},
  {"go test",           2},
  {"cargo test",        2},
  // script runners (mostly local code execution)
  {"npm run",           2},
  {"yarn run",          2},
  {"pnpm run",          2},
  {"npm test",          2},
  {"npm start",         2},

  // 1 — read-only / inspect
  {"ls",                1},
  {"cat",               1},
  {"head",              1},
  {"tail",              1},
  {"less",              1},
  {"more",              1},
  {"grep",              1},
  {"rg",                1},
  {"find",              1},
  {"pwd",               1},
  {"echo",              1},
  {"which",             1},
  {"whoami",            1},
  {"date",              1},
  {"stat",              1},
  {"file",              1},
  {"wc",                1},
  {"ps",                1},
  {"top",               1},
  {"htop",              1},
  {"uname",             1},
  {"uptime",            1},
  {"journalctl",        1},
  {"dmesg",             1},
  {"dig",               1},
  {"nslookup",          1},
  {"ping",              1},
  // git read
  {"git status",        1},
  {"git log",           1},
  {"git diff",          1},
  {"git show",          1},
  {"git branch",        1},
  {"git fetch",         1},
  {"git remote",        1},
  // orchestration / cloud read
  {"kubectl get",       1},
  {"kubectl describe",  1},
  {"kubectl logs",      1},
  {"helm list",         1},
  {"terraform plan",    1},
  {"docker ps",         1},
  {"docker images",     1},
  {"docker logs",       1},
  {"aws s3 ls",         1},
  // PowerShell read
  {"get-childitem",     1},
  {"get-content",       1},
  {"get-process",       1},
  {"get-service",       1},
  {"select-string",     1},
  {"test-path",         1},
  // macOS read
  {"defaults read",     1},
  {"mdfind",            1},
  {"system_profiler",   1},
  {"sw_vers",           1},
  {"ioreg",             1},
  {"vm_stat",           1},
  {"otool",             1},
  {"pbpaste",           1},
  // Cloudflare read
  {"wrangler tail",     1},
  {"wrangler whoami",   1},
  // git read
  {"git blame",         1},
  {"git reflog",        1},
  {"git ls-files",      1},
  {"git rev-parse",     1},
  {"git rev-list",      1},
  {"git shortlog",      1},
  {"git describe",      1},
  {"git archive",       1},
  {"git stash list",    1},
  {"git stash show",    1},
  // GitHub CLI (gh) read
  {"gh pr list",      1},
  {"gh pr view",      1},
  {"gh pr status",    1},
  {"gh pr diff",      1},
  {"gh pr checks",    1},
  {"gh issue list",   1},
  {"gh issue view",   1},
  {"gh issue status", 1},
  {"gh repo view",    1},
  {"gh repo list",    1},
  {"gh release list", 1},
  {"gh release view", 1},
  {"gh workflow list",1},
  {"gh workflow view",1},
  {"gh run list",     1},
  {"gh run view",     1},
  {"gh run watch",    1},
  {"gh search",       1},
  {"gh auth status",  1},
  {"gh gist list",    1},
  {"gh gist view",    1},
  {"gh secret list",  1},
  // linters / formatters / type checkers — read-only over the codebase
  {"eslint",          1},
  {"prettier",        1},
  {"black",           1},
  {"ruff",            1},
  {"mypy",            1},
  {"flake8",          1},
  {"gofmt",           1},
  {"go vet",          1},
  {"rustfmt",         1},
  {"clippy",          1},
  {"shellcheck",      1},
  // DB read tools
  {"pg_dump",         1},
  {"mysqldump",       1},
  // network / process inspect
  {"netstat",         1},
  {"ss",              1},
  {"lsof",            1},
  {"tcpdump",         1},
  {"tshark",          1},
  {"pgrep",           1},
  {"strace",          1},
  {"ltrace",          1},

  // file / directory inspection — what a coding agent actually reaches for
  {"tree",            1},
  {"diff",            1},
  {"cmp",             1},
  {"xxd",             1},
  {"hexdump",         1},
  {"od",              1},
  {"strings",         1},
  {"nm",              1},
  {"objdump",         1},
  {"readelf",         1},
  {"ldd",             1},
  {"size",            1},
  {"realpath",        1},
  {"readlink",        1},
  {"basename",        1},
  {"dirname",         1},
  // text processing — read / transform to stdout
  {"awk",             1},
  {"sed",             1}, // in-place override via "sed -i" at 3 below
  {"cut",             1},
  {"sort",            1},
  {"uniq",            1},
  {"tr",              1},
  {"column",          1},
  {"paste",           1},
  {"fold",            1},
  {"expand",          1},
  {"unexpand",        1},
  {"rev",             1},
  {"nl",              1},
  {"comm",            1},
  // hashes / checksums
  {"md5sum",          1},
  {"sha1sum",         1},
  {"sha256sum",       1},
  {"sha512sum",       1},
  {"shasum",          1},
  {"cksum",           1},
  // structured data query
  {"jq",              1},
  {"yq",              1},
  {"xq",              1},
  {"fx",              1},
  {"htmlq",           1},
  // env / docs / shell info
  {"printenv",        1},
  {"env",             1},
  {"man",             1},
  {"tldr",            1},
  {"info",            1},
  {"apropos",         1},
  {"whereis",         1},
  {"type",            1},
  {"command -v",      1},
  // identity / host
  {"id",              1},
  {"groups",          1},
  {"hostname",        1},
  {"tty",             1},
  // processes
  {"pstree",          1},
  {"pidof",           1},
  {"fuser",           1},
  // hardware / system
  {"lscpu",           1},
  {"lsblk",           1},
  {"lspci",           1},
  {"lsusb",           1},
  {"lshw",            1},
  {"lsmem",           1},
  {"lsmod",           1},
  // resource stats
  {"free",            1},
  {"df",              1},
  {"du",              1},
  {"iostat",          1},
  {"vmstat",          1},
  {"mpstat",          1},
  // archive read (listing / decompressing to stdout)
  {"tar -tf",         1},
  {"tar -tvf",        1},
  {"tar tf",          1},
  {"unzip -l",        1},
  {"zcat",            1},
  {"bzcat",           1},
  {"xzcat",           1},
  {"zless",           1},
  {"zgrep",           1},
  {"bzgrep",          1},
  {"xzgrep",          1},
  // git — more read paths
  {"git diff-tree",       1},
  {"git diff-index",      1},
  {"git ls-remote",       1},
  {"git cat-file",        1},
  {"git for-each-ref",    1},
  {"git grep",            1},
  {"git submodule status",1},
  {"git verify-commit",   1},
  {"git verify-tag",      1},
  {"git whatchanged",     1},
  {"git config --get",    1},
  {"git config --list",   1},
  {"git config -l",       1},
  // docker — read
  {"docker inspect",      1},
  {"docker stats",        1},
  {"docker top",          1},
  {"docker history",      1},
  {"docker diff",         1},
  {"docker version",      1},
  {"docker info",         1},
  // kubectl — read
  {"kubectl explain",     1},
  {"kubectl top",         1},
  {"kubectl auth can-i",  1},
  {"kubectl version",     1},
  {"kubectl api-resources",1},
  {"kubectl api-versions",1},
  {"kubectl config view", 1},
  // helm — read
  {"helm get",            1},
  {"helm history",        1},
  {"helm show",           1},
  {"helm status",         1},
  {"helm template",       1},
  {"helm diff",           1},
  {"helm version",        1},
  // aws — read
  {"aws sts get-caller-identity", 1},
  {"aws ec2 describe",    1},
  {"aws s3 cp",           1}, // typically downloads to local
  {"aws logs tail",       1},
  {"aws logs filter-log-events",  1},
  {"aws logs get-log-events",     1},
  {"aws cloudwatch get-metric",   1},
  // gcloud / az / doctl — read
  {"gcloud auth list",    1},
  {"gcloud config list",  1},
  {"gcloud projects list",1},
  {"gcloud compute instances list",1},
  {"az account show",     1},
  {"az group list",       1},
  {"doctl account get",   1},
};
